import type { CandidateArticle } from './candidateAcquisition';

export interface CandidateInventoryV3Config { activeBuffer:number; perInterestReserveCap:number; totalReserveCap:number; reserveTtlHours:number; }
export const DEFAULT_CANDIDATE_INVENTORY_V3_CONFIG: CandidateInventoryV3Config = { activeBuffer:1, perInterestReserveCap:30, totalReserveCap:120, reserveTtlHours:168 };
export interface SearchAcceptanceResultV3 { targetInterest:string; requestedDeficit:number; activeAcceptLimit:number; targetQualifiedUnique:number; activeAccepted:number; reserveInserted:number; duplicateOrExisting:number; reserveDroppedByCap:number; activeSupplyAfter:number; reserveSupplyAfter:number; }

function timestampMs(value:number|string|null|undefined):number|null { if(value==null)return null; if(typeof value==='number')return value>1e12?value:value*1000; const p=Date.parse(value); return Number.isFinite(p)?p:null; }
export function candidatePublicationAgeDaysV3(c:CandidateArticle,nowMs=Date.now()):number|null { const p=timestampMs(c.publishedAt??c.updatedAt); return p==null?null:Math.max(0,(nowMs-p)/86400000); }
function candidateRetrievalAgeHoursV3(c:CandidateArticle,nowMs=Date.now()):number|null { const p=timestampMs(c.retrievedAt); return p==null?null:Math.max(0,(nowMs-p)/3600000); }
export function supplyInterestV3(c:CandidateArticle):string|null { const t=typeof c.rawMetadata?.targetInterest==='string'?c.rawMetadata.targetInterest:null; if(c.qualified&&t&&(c.source==='search'||c.sourceOrigins.includes('search')))return t; return c.bestMatchedInterest??null; }

export class CandidateInventoryV3 {
  readonly active=new Map<string,CandidateArticle>();
  readonly reserve=new Map<string,CandidateArticle>();
  readonly used=new Set<string>();
  readonly wasted=new Set<string>();
  constructor(readonly config:CandidateInventoryV3Config=DEFAULT_CANDIDATE_INVENTORY_V3_CONFIG){}
  private eligible(c:CandidateArticle){return c.qualified&&!this.used.has(c.duplicateKey)}
  private stale(c:CandidateArticle,nowMs=Date.now()){const h=candidateRetrievalAgeHoursV3(c,nowMs);return h!=null&&h>this.config.reserveTtlHours}
  private score(c:CandidateArticle){const x=c.rawMetadata?.TARGET_INTEREST_SCORE;return typeof x==='number'?x:(c.bestSemanticScore??0)}
  private freshCmp(a:CandidateArticle,b:CandidateArticle,nowMs=Date.now()){const aa=candidatePublicationAgeDaysV3(a,nowMs)??Infinity,bb=candidatePublicationAgeDaysV3(b,nowMs)??Infinity;return aa-bb||this.score(b)-this.score(a)||a.sourceRank-b.sourceRank||a.duplicateKey.localeCompare(b.duplicateKey)}
  private sourceCmp(a:CandidateArticle,b:CandidateArticle){return a.sourceRank-b.sourceRank||this.score(b)-this.score(a)||a.duplicateKey.localeCompare(b.duplicateKey)}
  addRecommendation(rows:Iterable<CandidateArticle>){let n=0;for(const c of rows){const k=c.duplicateKey;if(!this.eligible(c)||this.active.has(k)||this.reserve.has(k))continue;this.active.set(k,c);n+=1}return n}
  pruneReserve(nowMs=Date.now()){let n=0;for(const [k,c] of [...this.reserve])if(this.used.has(k)||this.stale(c,nowMs)){this.reserve.delete(k);this.wasted.add(k);n+=1}return n}
  activeCounts(){const o:Record<string,number>={};for(const [k,c] of this.active){const i=supplyInterestV3(c);if(this.used.has(k)||!c.qualified||!i)continue;o[i]=(o[i]??0)+1}return o}
  reserveCounts(nowMs=Date.now()){this.pruneReserve(nowMs);const o:Record<string,number>={};for(const [k,c] of this.reserve){const i=supplyInterestV3(c);if(this.used.has(k)||!c.qualified||!i)continue;o[i]=(o[i]??0)+1}return o}
  private trimReserveCaps(nowMs=Date.now()){this.pruneReserve(nowMs);const by=new Map<string,CandidateArticle[]>();for(const c of this.reserve.values()){const i=supplyInterestV3(c);if(!i)continue;const xs=by.get(i)??[];xs.push(c);by.set(i,xs)}const keep=new Set<string>();for(const xs of by.values()){xs.sort((a,b)=>this.freshCmp(a,b,nowMs));for(const c of xs.slice(0,this.config.perInterestReserveCap))keep.add(c.duplicateKey)}const global=[...this.reserve.values()].filter(c=>keep.has(c.duplicateKey)).sort((a,b)=>this.freshCmp(a,b,nowMs));const finalKeep=new Set(global.slice(0,this.config.totalReserveCap).map(c=>c.duplicateKey));let d=0;for(const k of [...this.reserve.keys()])if(!finalKeep.has(k)){this.reserve.delete(k);this.wasted.add(k);d+=1}return d}
  activateReserve(interestId:string,requiredSupply:number,buffer=this.config.activeBuffer,nowMs=Date.now()){this.pruneReserve(nowMs);const current=this.activeCounts()[interestId]??0;const deficit=Math.max(0,Math.trunc(requiredSupply)-current);if(deficit<=0)return 0;const limit=deficit+Math.max(0,Math.trunc(buffer));const xs=[...this.reserve.values()].filter(c=>supplyInterestV3(c)===interestId&&this.eligible(c)).sort((a,b)=>this.freshCmp(a,b,nowMs));let moved=0;for(const c of xs.slice(0,limit)){this.reserve.delete(c.duplicateKey);this.active.set(c.duplicateKey,c);moved+=1}return moved}
  acceptSearchBatch(rows:Iterable<CandidateArticle>,targetInterest:string,requiredSupply:number,buffer=this.config.activeBuffer,acceptanceMode:'source_order'|'freshness_first'='source_order',nowMs=Date.now()):SearchAcceptanceResultV3 {this.pruneReserve(nowMs);const before=this.activeCounts()[targetInterest]??0;const requestedDeficit=Math.max(0,Math.trunc(requiredSupply)-before);const activeAcceptLimit=requestedDeficit>0?requestedDeficit+Math.max(0,Math.trunc(buffer)):0;const unique=new Map<string,CandidateArticle>();let duplicateOrExisting=0;for(const c of rows){const k=c.duplicateKey;if(!c.qualified||supplyInterestV3(c)!==targetInterest)continue;if(unique.has(k)||this.active.has(k)||this.reserve.has(k)||this.used.has(k)){duplicateOrExisting+=1;continue}unique.set(k,c)}const xs=[...unique.values()].sort((a,b)=>acceptanceMode==='freshness_first'?this.freshCmp(a,b,nowMs):this.sourceCmp(a,b));const aa=xs.slice(0,activeAcceptLimit),rr=xs.slice(activeAcceptLimit);for(const c of aa)this.active.set(c.duplicateKey,c);for(const c of rr)this.reserve.set(c.duplicateKey,c);const dropped=this.trimReserveCaps(nowMs);return{targetInterest,requestedDeficit,activeAcceptLimit,targetQualifiedUnique:xs.length,activeAccepted:aa.length,reserveInserted:Math.max(0,rr.length-dropped),duplicateOrExisting,reserveDroppedByCap:dropped,activeSupplyAfter:this.activeCounts()[targetInterest]??0,reserveSupplyAfter:this.reserveCounts(nowMs)[targetInterest]??0}}
  markUsed(keys:Iterable<string>){for(const k of keys){this.used.add(k);this.active.delete(k);this.reserve.delete(k)}}
}
