export const PRODUCT_V1_DOMAIN_LABELS: Record<string, string> = {
  AI: '人工智能',
  Anime: '动漫',
  Architecture: '建筑',
  Biology: '生物',
  Books: '阅读',
  Business: '商业',
  Career: '职业发展',
  Cars: '汽车',
  Cloud: '云计算',
  'Consumer Electronics': '消费电子',
  Crypto: '加密货币',
  Cybersecurity: '网络安全',
  Databases: '数据库',
  Design: '设计',
  'Digital Life': '数字生活',
  Economics: '经济学',
  Education: '教育',
  Embedded: '嵌入式',
  Entrepreneurship: '创业',
  Fashion: '时尚',
  Film: '影视',
  Finance: '金融',
  Fitness: '健身',
  Food: '美食',
  Games: '游戏',
  Hardware: '硬件',
  History: '历史',
  Home: '家居',
  Investing: '投资',
  Law: '法律',
  Lifestyle: '生活方式',
  Mathematics: '数学',
  Medicine: '医学',
  Mobile: '移动科技',
  Music: '音乐',
  'Open Source': '开源',
  'Operating Systems': '操作系统',
  Parenting: '育儿',
  Photography: '摄影',
  Physics: '物理',
  Politics: '政治',
  Programming: '编程',
  Psychology: '心理学',
  Quant: '量化',
  Relationships: '情感关系',
  Robotics: '机器人',
  Science: '科学',
  Sports: '体育',
  Technology: '科技',
  Travel: '旅行',
  Video: '视频',
};

export function productV1DomainLabel(domain: string) {
  return PRODUCT_V1_DOMAIN_LABELS[domain] ?? domain;
}
